FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt ./
COPY config.yaml ./
COPY payload_config.yaml ./
RUN echo "Rebuild"
COPY ingest/zmq_ingest_agent.py ./
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "zmq_ingest_agent.py"]
