FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt ./
COPY ui/streamlit_app.py ./
COPY data.db ./
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8501
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
