version: '3.8'
services:
  ingest_agent:
    build:
      context: .
      dockerfile: Dockerfile.ingest_agent
    volumes:
      - ./data.db:/app/data.db
      - ./config.yaml:/app/config.yaml
      - ./payload_config.yaml:/app/payload_config.yaml
    ports:
      - "5555:5555"
  mqtt_connector:
    build:
      context: ./connector
      dockerfile: Dockerfile.mqtt_connector
    depends_on:
      - ingest_agent
    volumes:
      - ./connector/mqtt_config.yaml:/app/mqtt_config.yaml
    environment:
      - PYTHONUNBUFFERED=1
  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    depends_on:
      - ingest_agent
    ports:
      - "8501:8501"
    volumes:
      - ./data.db:/app/data.db
