FROM python:3.10-slim
WORKDIR /app
COPY ../requirements.txt ./
COPY mqtt_config.yaml ./
COPY mqtt_connector.py ./
RUN pip install --no-cache-dir -r requirements.txt
CMD ["python", "mqtt_connector.py"]
